# Generated by Django 5.1.7 on 2025-04-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=255)),
                ('categoria_image', models.ImageField(blank=True, upload_to='photos/categories/')),
            ],
        ),
    ]
