# Generated by Django 5.1.7 on 2025-04-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
