# Generated by Django 5.1.7 on 2025-04-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categorias_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='descricao',
            new_name='categoria_descricao',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='categoria_image',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='categorias_name',
        ),
        migrations.AddField(
            model_name='categorias',
            name='categoria_imagem',
            field=models.ImageField(blank=True, upload_to='fotos/categorias/'),
        ),
        migrations.AddField(
            model_name='categorias',
            name='categorias_nome',
            field=models.CharField(default='produtos zero lactos', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
